### PR TITLE
Update s3dis_data_utils.py

### PR DESCRIPTION
**Pull request by cs1488**
Used fix as described in #1949

## Motivation
Stumbled over this today and then found the open issue

## Modification
Changed data type

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @cs1488 ,

Thanks for your kind contribution. Would you like to fix the lint issue so that we could merge this PR?
The details can be found by clicking the item of lint check as shown below
image

**Comment by cs1488** [comment]
Hello @ZwwWayne,
this is my first pull request, so i am not totally sure i did what you requested.
But i updated the file accordingly to the lint issue.
I am not sure how i could perform if any tests to verify that this fixes the issue but i hope it does.
I do not know what to do about the other failings/errors.
Kind Regards

**Comment by Xiangxu-0103** [comment]
> Hello @ZwwWayne, this is my first pull request, so i am not totally sure i did what you requested. But i updated the file accordingly to the lint issue. I am not sure how i could perform if any tests to verify that this fixes the issue but i hope it does. I do not know what to do about the other failings/errors. Kind Regards

You can use pre-commit to fix the lint problem following this [guidance](https://github.com/open-mmlab/mmengine/blob/main/docs/en/notes/contributing.md#2-configure-pre-commit).

**Comment by Xiangxu-0103** [comment]
You may need to pull the latest code which has fixed the lint issue.

**Review by Xiangxu-0103 — COMMENTED** [review]
@cs1488 Please merge the latest dev branch and fix the lint issue.

**Comment by cs1488** [comment]
I tried, i can not run the tools you linked.
I fetched some dev branch, and on the checks it says lint is fine see image for that
lint

I do not know about the other stuff.

**Review by Xiangxu-0103 — APPROVED** [review]

**Comment by vansin** [comment]
@cs1488 Congratulations on having your first PR merged in OpenMMLab! I am a technical operations staff member of OpenMMLab. My WeChat ID is **van-sin** ,please add me . I would like to invite you to join the OpenMMLab contributors WeChat group.

**Pull request merged**
