### PR TITLE
[Enhance] Update numba version

### PR DESCRIPTION
**Pull request by ZCMax**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
This PR is trying to fix some warnings and errors while updating numba from 0.48.0 to 0.54.1 and refactor some code to speed up training.

## Modification
for \@cuda.jit, transform eager compilation to Lazy compilation.
for some ops, we refactor the code.
add eager compilation to \@numba.njit, to speed up compilation speed.

## BC-breaking (Optional)
no

## Use cases (Optional)
n/a

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by ZCMax** [comment]
Note that some modifications are still on going. To verify the modifications' effect, some experiments need to be done.

**Comment by ZwwWayne** [comment]
Should we also update the version of numba in requirements.txt?

**Comment by ZCMax** [comment]
> Should we also update the version of numba in requirements.txt?

yes,I'll add it to this PR soon

**Comment by ZwwWayne** [comment]
Kindly ping @ZCMax

**Comment by ZwwWayne** [comment]
Can be merged after resolving conflicts.

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
