### PR TITLE
[Fix] fix pointpillars_waymo in `dev-1.x`

### PR DESCRIPTION
**Pull request by Xiangxu-0103**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

For the waymo dataset, the classes is `[Car, Pedestrian, Cyclist]`, while for `PointPillars` model, the classes is `[Car, Cyclist, Pedestrian]`, which is inconsistency with the order of dataset classes

**Benchmark (training on 8 GPUs)**:
|                    anchor size                    | car (L2 mAPH) | pedestrian (L2 mAPH) | cyclist (L2 mAPH) |
| :--------------------------------------------: | :---: | :-----: | :------: |
| old cfg |  55.1  |   43.6   |   48.7   | 
 new cfg|  56.9  |   44.2  |   52.7    | 

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by Tai-Wang** [comment]
@ZCMax @lianqing11 Please check the effect of this bug fix on the previous benchmark/model preparation.

**Comment by JingweiZhang12** [comment]
@Xiangxu-0103 . Thanks for your PR.
1. Please pull the latest code and resolve the conflicts.
2. The commit log of this PR is messy. Please reorganize it. If necessary, please split it into several PRs.

**Review by JingweiZhang12 — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Should we benchmark the model and check the performance?

**Comment by JingweiZhang12** [comment]
> Should we benchmark the model and check the performance?
Have benchmarked.

**Comment by JingweiZhang12** [comment]
**Benchmark (training on 16 GPUs)**:
|                    anchor size                    | car (L2 mAPH) | pedestrian (L2 mAPH) | cyclist (L2 mAPH) |
| :--------------------------------------------: | :---: | :-----: | :------: |
| old cfg |  60.7 |   45.1  |   53.6   | 
 new cfg|  60.1  |   44.1  |   50.8    |

**Pull request merged**
