### PR TITLE
[Refactor] Camera keys

### PR DESCRIPTION
**Pull request by filaPro**
1. Remove legacy keys from `Collect3D`: `rect`, `Trv2c`, `P2`.
2. Rename `cam_intrinsic` to `cam2img` to be consistent with `depth2img` and `lidar2img`. In next PRs this can unify image dependent functions like visualization and point fusion. More discussion in [#791#issuecomment-887258262](https://github.com/open-mmlab/mmdetection3d/pull/791#issuecomment-887258262).

### CODE REVIEW

**Review by Wuziyi616 — COMMENTED** [review]
I assume that you have used Ctrl+F to find and replace all the `cam_intrinsic` to `cam2img`? Also, please kindly test the code by `browse_dataset.py` on nuScene mono dataset and running the mono3d detection demo to check the visualization results. Thanks!

**Comment by filaPro** [comment]
> I assume that you have used Ctrl+F to find and replace all the `cam_intrinsic` to `cam2img`?

Unfortunately, no, as we have some `cam_intrinsic` in KITTI, nuScenes and Lyft annotations. So I replaced them only after loading pipelines. So, after `Collect3D` we will not have `cam_intrinsic`. But for visualization and browse dataset will probably keep it.

> Also, please kindly test the code by `browse_dataset.py` on nuScene mono dataset and running the mono3d detection demo to check the visualization results.

Ok will try to visualize.

**Comment by Wuziyi616** [comment]
> 
> 
> > I assume that you have used Ctrl+F to find and replace all the `cam_intrinsic` to `cam2img`?
> 
> Unfortunately, no, as we have some `cam_intrinsic` in KITTI, nuScenes and Lyft annotations. So I replaced them only after loading pipelines. So, after `Collect3D` we will not have `cam_intrinsic`. But for visualization and browse dataset will probably keep it.
> 
> > Also, please kindly test the code by `browse_dataset.py` on nuScene mono dataset and running the mono3d detection demo to check the visualization results.
> 
> Ok will try to visualize.

That makes sense. Looking forward to the visualization results :)

**Comment by filaPro** [comment]
Hi @Tai-Wang, @Wuziyi616,

Monocular demo seems to be broken and not by my commits. Am I missing something?
n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_pred

**Comment by Tai-Wang** [comment]
Hi @filaPro , that's due to code refactoring for removing hacks in the previous codes. See #744 and #794 . The pretrained model link should be updated in the documentation (I will create a PR to fix that). You can try to pull the latest code and use the updated checkpoints. Everything seems fine from my side.

**Comment by filaPro** [comment]
> You can try to pull the latest code and use the updated checkpoints

Really I pulled master and downloaded the checkpoint today. Will check one more time.

**Comment by Tai-Wang** [comment]
> > You can try to pull the latest code and use the updated checkpoints
> 
> Really I pulled master and downloaded the checkpoint today. Will check one more time.
> 
> UPD. Sorry for that. Master branch is fine.

Never mind :) Thank you for reminding me the link has not been updated. It really makes that example confusing.

**Comment by filaPro** [comment]
@Tai-Wang, looks like `browse_dataset` is also broken. [Here](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/misc/browse_dataset.py#L176) we have not enough parameters for `show_multi_modality_result` call. Am I right?

**Comment by Tai-Wang** [comment]
@filaPro That seems a legacy bug. It is not introduced by my refactoring, but I will create a PR to fix that.

After fix the missing parameter, everything is ok for me. Have you re-generated the json files after merging the master? I have removed the hacks by adding some transformations in the pre-processing and post-processing. See more details in the compatibility [documentation](https://mmdetection3d.readthedocs.io/en/latest/compatibility.html).

**Comment by filaPro** [comment]
@Wuziyi616, @Tai-Wang `browse_dataset` and `mono_det_demo` are fine.
n015-2018-07-18-11-07-57+0800__CAM_FRONT__1531883530912460_gt
n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_pred

**Review by Wuziyi616 — APPROVED** [review]
The visualization seems to be good. Great job!

**Review by Tai-Wang — APPROVED** [review]

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
