### PR TITLE
[Refactor] visualize_results.py 

### PR DESCRIPTION
**Pull request by lehnasamia**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
I want to visualize my result generated by the test of the mvx model on kittiDataset.  

## Modification

We have to modify the visualize_results.py because it's not compatible with MMengine. Now to visualize the results we use mmcv. 

## BC-breaking (Optional)

Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by JingweiZhang12** [comment]
@lehnasamia Thanks for your PR. You can refer to [contribution_guides](https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/docs/en/notes/contribution_guides.md) to refine your PR.

**Comment by JingweiZhang12** [comment]
@lehnasamia Hi, maybe you don't commit your modification based on the dev-1.x branch so that there are a lot of commits of others. We suggest that you can checkout a new branch from dev-1.x branch and modify the code on this new branch.

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @lehnasamia,

We'd like to express our appreciation for your valuable contributions to the mmdetection3d. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Comment by JingweiZhang12** [comment]
@lehnasamia Hi， I have updated my email and you could send the error log to my email again.

**Pull request merged**
