### PR TITLE
Explicitly setting torch.cuda.device at init_model

### PR DESCRIPTION
**Pull request by aldakata**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
#1055 

## Modification
Explicitly setting the cuda device before model.to(device)

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @aldakata ,
Could you sign the CLA so that we can merge this PR?

**Comment by aldakata** [comment]
Signed!

**Comment by ZwwWayne** [comment]
It seems that this issue is caused in CenterPoint, we will fix the root issue in CenterPoint rather than in the inference API.

**Comment by wHao-Wu** [comment]
Hi, @aldakata 
Thanks for your feedback and contribution. We found that other spconv-based models will also cause this problem. We will fix the spconv problem in ops directly in the future.

**Comment by OpenMMLab-Coodinator** [comment]
Hi @aldakata , first of all, we want to express our gratitude for your significant PR in the MMDet3d project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! **Join us ：https://discord.gg/raweFPmdzG**

If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
