### PR TITLE
[Fix] fix pointpillars bug on kitti in master branch

### PR DESCRIPTION
**Pull request by ZCMax**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
This PR solves two major bugs in PointPillars on kitti dataset which will drop the performance.
1. Change the anchor range in config, to solve the misalignment problem of anchors.
2. in kitti_dataset,  "difficulty" is not stored in the returned dict, so all objects are given difficulty "0", hence nothing being filtered for cut and paste.

## Modification
1. add "difficulty" in returned dict for filtering the objects correctly.
2. modify the anchor range in config for center alignment.

## BC-breaking (Optional)
no

## Use cases (Optional)
N/A

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by ZwwWayne — COMMENTED** [review]
Does difficulty affect the performance of other models？

**Comment by ZCMax** [comment]
>

**Comment by ZCMax** [comment]
> Does difficulty affect the performance of other models？

Good question, I'll experiment the setting on other models.

**Review by Tai-Wang — APPROVED** [review]

**Comment by ZCMax** [comment]
The models like centerpoint and second would not be affected while updating the difficulty filter augmenation.

**Comment by ZCMax** [comment]
I've tested the influence of fixing the bug of `filter_by_difficulty` on SECOND and Parta2 models, it will bring minor performance improvements.

**Review by Tai-Wang — APPROVED** [review]

**Pull request merged**
