### PR TITLE
[Fix] Centerpoint head nested list transpose 

### PR DESCRIPTION
**Pull request by robin-karlsson0**
This PR improves how the nested lists are transposed in the function `def get_targets(self, gt_bboxes_3d, gt_labels_3d)`.

## Motivation
The old implementation requires PyTorch tensors to be transformed into Numpy arrays, and then back again to PyTorch tensors, in the processes requiring moving memory back and forth between GPU and CPU. The new implementation instead utilize a simple Python nested list transpose operation which works natively on lists of PyTorch tensors in GPU memory.

Encountered the same error as described in issue https://github.com/open-mmlab/mmdetection3d/issues/387. Don't think relying on a particular old version of Numpy resulting in some unknown-but-working behaviour is a solid fix, and thus the PR.

## Modification
Replaces the following Numpy-based nested list transpose code
`heatmaps = np.array(heatmaps).transpose(1, 0).tolist()`
with
`heatmaps = list(map(list, zip(*heatmaps)))`

The modification is tested and currently running on an experiment.

### CODE REVIEW

**Comment by THU17cyz** [comment]
In this issue #588 , this part of code leads to a bug when the NumPy version is too low. Your fix is a solid one and removes the dependency on an appropriate NumPy version. Thank you for your contribution!

**Review by THU17cyz — APPROVED** [review]

**Review by Tai-Wang — APPROVED** [review]

**Comment by ZwwWayne** [comment]
I think if the model tests well, we can merge this PR.

**Comment by robin-karlsson0** [comment]
Thank you all for reviewing the PR!

> I think if the model tests well, we can merge this PR.
@ZwwWayne I can confirm that my test experiment with the changed code resulted in similar APs after 1 epoch as those of the prior GPU --> CPU --> GPU Numpy code.

**Comment by OpenMMLab-Coodinator** [comment]
Hi @robin-karlsson0 ！First of all, we want to express our gratitude for your significant PR in the MMDet3d project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
