### PR TITLE
fix bbox direction

### PR DESCRIPTION
**Pull request by zhulf0804**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

When training PointPillars, the bbox direction gt label is set to 0 when the angle is between in [0, np.pi] and  is set to 1 when the angle is between in [np.pi, 2*np.pi]. 

https://github.com/open-mmlab/mmdetection3d/blob/ed81c6cc326a33f927d4455c219bb7715591b08b/mmdet3d/models/dense_heads/train_mixins.py#L336-L338

However, in the test stage, the operation may be opposite. That is the predicted label 0 corresponds to [-np.pi, 0] or [np.pi, 2*np.pi], while the predicted label 1 corresponds to [0, np.pi]

https://github.com/open-mmlab/mmdetection3d/blob/ed81c6cc326a33f927d4455c219bb7715591b08b/mmdet3d/models/dense_heads/anchor3d_head.py#L506-L511

## Modification

I modified in predicted bbox prediction ([mmdet3d/models/dense_heads/anchor3d_head.py#L506-L511](https://github.com/open-mmlab/mmdetection3d/blob/ed81c6cc326a33f927d4455c219bb7715591b08b/mmdet3d/models/dense_heads/anchor3d_head.py#L506-L511)) as the following code:

```
if bboxes.shape[0] > 0:
            dir_rot = limit_period(bboxes[..., 6] - self.dir_offset,
                                   self.dir_limit_offset, np.pi)
            bboxes[..., 6] = (
                dir_rot + self.dir_offset + np.pi *
                (1 - dir_scores.to(bboxes.dtype)))
```

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by ZwwWayne** [comment]
Hi @zhulf0804 ,
Thanks for your kind PR. Could you fix the lint issue? You can find more details here.
image

**Comment by zhulf0804** [comment]
Thank you for your approval. I'll fix it as soon as possible. Best wishes. Lifa. 朱立发 ***@***.*** 签名由 网易邮箱大师 定制 On 03/22/2022 23:38, Wenwei Zhang wrote: Hi @zhulf0804 , Thanks for your kind PR. Could you fix the lint issue? You can find more details here. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Tai-Wang** [comment]
This bug seems to be fixed in the latest mmdet3d. I found your used version is about v0.16.0. This bug can be fixed via setting the `dir_limit_offset` to 0 to keep it consistent with that in `get_direction_target`. You can also refer to this [issue](https://github.com/traveller59/second.pytorch/issues/238) in SECOND for more details.

**Review by Tai-Wang — CHANGES_REQUESTED** [review]
Please double-check whether this problem exists in the latest mmdet3d. I guess it has been fixed as I commented.

**Comment by zhulf0804** [comment]
> 

Thank you for your quick reply. I checked that It has been fixed in both master and [v1.0.0rc0](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc0). 
However, I just used the previous  version [v0.18.1](https://github.com/open-mmlab/mmdetection3d/tree/v0.18.1). 

I thought I used a very new version, because  [v0.18.1](https://github.com/open-mmlab/mmdetection3d/tree/v0.18.1) was released on Feb 09, 2022.  I'm sorry for not checking the latest version before asking the question. 

By the way, I found the bug was fixed in [#803](https://github.com/open-mmlab/mmdetection3d/pull/803) on Jul 29, 2021. 
Then It was not updated until recently in [v1.0.0rc0](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc0) version 22 days ago (maybe on Mar 1, 2022.). I wonder why not considering updating it in earlier versions ? 

Looking forward to your reply.

Anyway, nice repo and implementations.

**Pull request closed without merging**
