### PR TITLE
[Fix] fix SECOND Waymo results

### PR DESCRIPTION
**Pull request by happynear**
The results of SECOND on Waymo do not match the log file. The results on README are too low.

README:
| [SECFPN]|5|3 Class|2x|8.12||58.0|53.5|51.5|48.3|log|
| above @ Car|||2x|8.12||58.5|57.9|51.6|51.1| |
| above @ Pedestrian|||2x|8.12||63.9|54.9|56.0|48.0| |
| above @ Cyclist|||2x|8.12||48.6|47.6|46.8|45.8| |

LOG:
{"mode": "val", "epoch": 24, "iter": 1977, "lr": 1e-05, "Vehicle/L1 mAP": 0.67149, "Vehicle/L1 mAPH": 0.66598, "Vehicle/L2 mAP": 0.58660, "Vehicle/L2 mAPH": 0.58173, "Pedestrian/L1 mAP": 0.68099, "Pedestrian/L1 mAPH": 0.59131, "Pedestrian/L2 mAP": 0.59516, "Pedestrian/L2 mAPH": 0.51546, "Sign/L1 mAP": 0.0, "Sign/L1 mAPH": 0.0, "Sign/L2 mAP": 0.0, "Sign/L2 mAPH": 0.0, "Cyclist/L1 mAP": 0.60655, "Cyclist/L1 mAPH": 0.59519, "Cyclist/L2 mAP": 0.58416, "Cyclist/L2 mAPH": 0.57321, "Overall/L1 mAP": 0.65301, "Overall/L1 mAPH": 0.61749, "Overall/L2 mAP": 0.58864, "Overall/L2 mAPH": 0.55680}

### CODE REVIEW

**Comment by Tai-Wang** [comment]
Thanks for your kind correction. I just found the PR for enhancing SECOND results on Waymo in the [changelog](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/changelog.md) has also incorrect PR number/link (Improvements in v0.8.0, Enhance SECOND benchmark on Waymo with stronger baselines. (#166) -> Enhance SECOND benchmark on Waymo with stronger baselines. (#205) ). Could you please also modify it in this PR?

**Review by Tai-Wang — APPROVED** [review]

**Comment by happynear** [comment]
Seems that this PR(https://github.com/open-mmlab/mmdetection3d/pull/205) didn't modify the results in README, but changed the log.

**Comment by Tai-Wang** [comment]
> Seems that this PR(#205) didn't modify the results in README, but changed the log.

Yes it's my carelessness at that time (both the PR number in the changelog & the PR for updating benchmark not changing the README). I just want you to help modify the changelog by the way.

**Comment by happynear** [comment]
OK, I changed the PR number.

**Comment by OpenMMLab-Assistant-007** [comment]
Hi!
@happynear 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
