### PR TITLE
the first version of semantic-kitti dataset

### PR DESCRIPTION
**Pull request by Jacky-gsq**
This PR is the first version of the code for supporting the semantic-kitti dataset and related to the issue  #1350 

It mainly includes:

1. The implementation of` evaluate `function in `SemanticKittiDataset`
2. The pipeline for loading the `calib` and `pose` information in the dataset
3. The unit test for the above code

There are still some problems with details and looking forward to your advice.

### CODE REVIEW

**Review by Jacky-gsq — COMMENTED** [review]
Please review the PR.
Sorry for forgetting to add the reviewer.

**Comment by ZCMax** [comment]
Please fix the CI problems ~~

**Comment by Tai-Wang** [comment]
Hi @Jacky-gsq , please use the pre-commit hook to check your codes such that the commits can pass the CI. You can follow this [guide](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) for more details.

**Comment by Jacky-gsq** [comment]
@Tai-Wang OK, I will commit the code again under the guide!

**Pull request closed without merging**
